// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4i7HR2lY9tERx1M8MYWa1naFOAtyRaVk',
    appId: '1:5429794817:web:81ac783a60a6c380768800',
    messagingSenderId: '5429794817',
    projectId: 'cancer-ml-6b421',
    authDomain: 'cancer-ml-6b421.firebaseapp.com',
    storageBucket: 'cancer-ml-6b421.appspot.com',
    measurementId: 'G-PPJNMFHW0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2RCo1h7ozq2s0LSIR8kaJoyAmxmdWrw',
    appId: '1:5429794817:android:95e3fe684f74a850768800',
    messagingSenderId: '5429794817',
    projectId: 'cancer-ml-6b421',
    storageBucket: 'cancer-ml-6b421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbJygYlgE2wzDVUk-gNzjDDUxUCQHo-u8',
    appId: '1:5429794817:ios:ee98adaf76d91326768800',
    messagingSenderId: '5429794817',
    projectId: 'cancer-ml-6b421',
    storageBucket: 'cancer-ml-6b421.appspot.com',
    iosClientId: '5429794817-is8gdfosfjsu26ve0birkfrvouv9l69u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfliteTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbJygYlgE2wzDVUk-gNzjDDUxUCQHo-u8',
    appId: '1:5429794817:ios:ee98adaf76d91326768800',
    messagingSenderId: '5429794817',
    projectId: 'cancer-ml-6b421',
    storageBucket: 'cancer-ml-6b421.appspot.com',
    iosClientId: '5429794817-is8gdfosfjsu26ve0birkfrvouv9l69u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfliteTest',
  );
}
